# Семинар 2

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [2]:
import numpy as np

In [2]:
# Создание одномерного вектора
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
# Создание двумерной матрицы
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [5]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [7]:
# Тип данных – целые числа (int)
# На вашем компьютере это может выглядет как int16, int32 или int64 – главное, что int!
vec.dtype

dtype('int64')

In [8]:
type(vec)

numpy.ndarray

Размер массива:

In [9]:
# 3 строки, 2 столбца – как в обычных математических матрицах!
vec.shape

(3, 2)

Число осей:

In [10]:
# Две оси: строки и столбцы
vec.ndim
# Математика позволяет иметь неограниченное число осей:
# 1 ось ~ одномерный вектор чисел
# 2 оси ~ матрица
# 3 оси ~ тензор (а-ля трёхмерная матрица)
# 4 оси ~ ??? (тоже какой-то объект)
# Сложно представить, но теория позволяет!

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [11]:
# Найти сумму по всем элементам массива
np.sum(vec)

21

In [12]:
# Найти сумму вдоль строк (оси 0) = по столбцам
np.sum(vec, axis=0)

array([ 9, 12])

In [13]:
# Найти сумму вдоль столбцов (оси 1) = по строкам
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [14]:
?np.sum

In [15]:
# np.sum() – функция numpy, vec.sum() – метод массива numpy
vec.sum()

21

Транспонируем массив:

In [16]:
# Как в обычной математике
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [18]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
vec.shape

(3, 2)

Размеры массивов можно менять:

In [20]:
# Измкнить форму. Заполняется по строкам (1-2-3-...)
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
vec.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
vec.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
# Если размер некорректен, появится ошибка
vec.reshape(10, 5)

ValueError: cannot reshape array of size 6 into shape (10,5)

In [24]:
# -1 = "поставь любое число на это место, чтобы соблюсти правильный размер"
# В данном случае мы хотим получить 3 столбца, а количество строк просим сделать любым подходящим
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Numpy делает различие между векторами (одна ось) и матрицами (две оси)

# Вектор в numpy: только одна ось!
# Это не матрица размера 3x1!!
a = np.array([1, 2, 3])
a.shape

(3,)

In [30]:
a

array([1, 2, 3])

In [28]:
# А вот теперь – матрица размера 3x1, две оси
a = a.reshape(3, 1)
a.shape

(3, 1)

Индексирование:

In [32]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
vec[:, 1]

array([2, 4, 6])

In [33]:
vec[2, :]

array([5, 6])

In [34]:
vec[1:2, 0]

array([3])

In [35]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

Булевы массивы:

In [37]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [38]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [39]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [40]:
vec[vec % 2 == 0]

array([2, 4, 6])

In [41]:
vec[vec == 3]

array([3])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [42]:
# Точки после чисел = сокращения от 0.0 (западная традция: если после запятой ничего не стоит, то есть стоит 0,
# то ничего и не пишут)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [46]:
# Опять сокращения от 1.0
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
# Тип – числа с плавающей запятой
a.dtype

dtype('float64')

Единичная матрица:

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [48]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
# Вдоль строк
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [50]:
# Вдоль столбцов
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
np.array([1, 2, 3])

array([1, 2, 3])

И, наконец - арифметические операции!

In [52]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
# Все арифметические операции выполняются поэлементно!
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [54]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [55]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [56]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [57]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [58]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [ ]:
# Обычное матричное умножение
A.dot(B)
A @ B # значок работает только в Python 3, в Python 2 не получится

In [59]:
# У матриц не совпадают размеры
vec.dot(vec ** 2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [60]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [61]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [62]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [64]:
# Broadcasting = "дополнение" объекта так, чтобы его можно было, например, сложить с другим объектом
# В данном случае к матрице размера 3х2 прибавляется вектор размера 3х1
# Математически это не имеет смысла, но numpy "предполагает", что мы хотим прибавить вектор-столбец 
# к каждому столбцу матрицы
vec + np.arange(3).reshape(3, 1)

# Если сомневаетесь, как сработает broadcasting – создавайте объекты в явном виде!
# В данном примере – создать матрицу с двумя одинаковыми столбцами, каждый из которых равен np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [74]:
np.random.rand(2, 3)

array([[0.855038  , 0.70248562, 0.54736211],
       [0.76611607, 0.3534031 , 0.94946336]])

In [66]:
?np.random.rand

In [9]:
# Генератор случайных чисел – на самом деле, сложная математическая функция, в которую подаётся некоторое число
# Выдаваемое этой функций число = псевдо-случайное число, которое и выдаёт numpy
# Чтобы добиться воспроизводимости результатов, нужно установить seed, который и будет подаваться в эту функцию
# В качестве seed можно установить (почти) любое число
np.random.seed(2019) # или 123, или 763, или 1, или ...
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [10]:
# Как работает seed:
# после каждого фиксирования seed при запуске одинаковых функций будут выдаваться одинаковые случайные числа
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [11]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [12]:
# если не фиксировать seed каждый раз, то будут выдаваться разные случайные числа
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [13]:
np.random.rand(2, 3)

array([[0.70219827, 0.90320616, 0.88138193],
       [0.4057498 , 0.45244662, 0.26707032]])

In [14]:
np.random.rand(2, 3)

array([[0.16286487, 0.8892147 , 0.14847623],
       [0.98472349, 0.03236122, 0.51535075]])

In [15]:
# но последовательность всегда сохраняется
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [16]:
np.random.rand(2, 3)

array([[0.70219827, 0.90320616, 0.88138193],
       [0.4057498 , 0.45244662, 0.26707032]])

In [17]:
np.random.rand(2, 3)

array([[0.16286487, 0.8892147 , 0.14847623],
       [0.98472349, 0.03236122, 0.51535075]])

In [ ]:
# Другие примеры:

In [160]:
np.random.randn(3, 2)

array([[ 0.0169049 , -0.51498352],
       [ 0.24450929, -0.18931261],
       [ 2.67217242,  0.46480249]])

In [161]:
np.random.normal(2, 1, size=3)

array([2.84593044, 1.49645842, 1.03666447])

In [162]:
np.random.randint(5, 10, size=3)

array([7, 7, 6])

Почему вообще используют `numpy`?

In [163]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [164]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 18.4 s, sys: 51.7 ms, total: 18.5 s
Wall time: 18.5 s


In [165]:
%%time
C = A @ B
# Вывод: всегда используйте numpy, а не циклы!!!

CPU times: user 20.3 ms, sys: 8.15 ms, total: 28.5 ms
Wall time: 15.2 ms


In [ ]:
# Библиотеки для проведения ещё более быстрых вычислений
# jax
# numba

### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).

In [169]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [170]:
np.flip(a)

array([3, 2, 1])

2. Найти максимальный нечетный элемент в массиве.

In [173]:
np.max(a[a % 2 != 0])

3

3. Замените все нечетные элементы массива на ваше любимое число.

In [174]:
fav_number = 123
b = a.copy() # безопасно! Не нужно переживать, что поменяем оригинальный массив
b[b % 2 != 0] = fav_number

In [175]:
b

array([123,   2, 123])

In [176]:
a

array([1, 2, 3])

In [ ]:
a = b

4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*

In [186]:
# Пример, как писать документацию к функции
def array_of_n_odd_numbers(n):
    '''
    Returns a flipped array of odd numbers from 1 to n.
    
    Arguments:
    ----
    n: int
        Number of numbers
        
    Returns:
    ----
        Flipped array of odd numbers from 1 to n.
    
    '''
    
    return np.flip(np.arange(1, (2 * n), 2))

In [184]:
array_of_n_odd_numbers(5)

array([9, 7, 5, 3, 1])

In [185]:
array_of_n_odd_numbers(9)

array([17, 15, 13, 11,  9,  7,  5,  3,  1])

In [187]:
# Написанная документация отобразится здесь
?array_of_n_odd_numbers

5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [189]:
def closest_farthest(arr, num):
    closest_pos = np.argmin(np.abs(arr - num)) # выдаются индексы
    farthest_pos = np.argmax(np.abs(arr - num)) 
    
    return (arr[closest_pos], arr[farthest_pos])

In [190]:
closest_farthest(np.array([0, 1, 2, 3, 4]), 1.33)

(1, 4)

In [191]:
closest_farthest(np.array([-1, 100, 12, 3, 4]), -5)

(-1, 100)

6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_

In [192]:
def antidervative(arr):
    powers = np.flip(np.arange(1, len(arr) + 1))
    antider = arr / powers
    antider = np.append(antider, -2)
    
    return antider

In [193]:
antidervative(np.array([4, 6, 0, 1]))

array([ 1.,  2.,  0.,  1., -2.])

7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# Что должно получиться:
# 4x^3 + 6x^2 + 1
# [4, 6, 0, 1]

# 12x^2 + 12x
# [12, 12, 0]

In [202]:
def derivative(arr, point):
    
    powers = np.flip(np.arange(0, len(arr)))
    print(powers)
    coefs = arr * powers
    coefs = coefs[:-1]
    
    new_powers = powers - 1
    new_powers = new_powers[:-1]
    
    point_array = point * np.ones(len(new_powers))
    powered_point = np.power(point_array, new_powers)
    deriv = np.sum(powered_point * coefs)
    
    return (coefs, deriv)

In [204]:
derivative(np.array([4, 6, 0, 1]), 0)

[3 2 1 0]


(array([12, 12,  0]), 0.0)